parcelRequire=function(e,r,t,n){var i,o="function"==typeof parcelRequire&&parcelRequire,u="function"==typeof require&&require;function f(t,n){if(!r[t]){if(!e[t]){var i="function"==typeof parcelRequire&&parcelRequire;if(!n&&i)return i(t,!0);if(o)return o(t,!0);if(u&&"string"==typeof t)return u(t);var c=new Error("Cannot find module '"+t+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[t][1][r]||r},p.cache={};var l=r[t]=new f.Module(t);e[t][0].call(l.exports,p,l,l.exports,this)}return r[t].exports;function p(e){return f(p.resolve(e))}}f.isParcelRequire=!0,f.Module=function(e){this.id=e,this.bundle=f,this.exports={}},f.modules=e,f.cache=r,f.parent=o,f.register=function(r,t){e[r]=[function(e,r){r.exports=t},{}]};for(var c=0;c<t.length;c++)try{f(t[c])}catch(e){i||(i=e)}if(t.length){var l=f(t[t.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=l:"function"==typeof define&&define.amd?define(function(){return l}):n&&(this[n]=l)}if(parcelRequire=f,i)throw i;return f}({"q7Av":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react"),t=require("react/jsx-runtime");function a(e,t,a){return t in e?Object.defineProperty(e,t,{value:a,enumerable:!0,configurable:!0,writable:!0}):e[t]=a,e}class s extends e.Component{constructor(...e){super(...e),a(this,"state",{active:0}),a(this,"handleIndexClick",e=>{this.setState({active:+e.target.dataset.index})})}render(){const{active:e}=this.state,{images:a}=this.props;return(0,t.jsxs)("div",{className:"carousel",children:[(0,t.jsx)("img",{src:a[e],alt:"animal"}),(0,t.jsx)("div",{className:"carousel-smaller",children:a.map((a,s)=>(0,t.jsx)("img",{src:a,"data-index":s,onClick:this.handleIndexClick,className:s===e?"active":"",alt:"animal thumbnail"},a))})]})}}a(s,"defaultProps",{images:["http://pets-images.dev-apis.com/pets/none.jpg"]});var i=s;exports.default=i;
},{}],"izif":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react"),r=require("react-router-dom"),t=require("react/jsx-runtime");function o(e,r,t){return r in e?Object.defineProperty(e,r,{value:t,enumerable:!0,configurable:!0,writable:!0}):e[r]=t,e}class s extends e.Component{constructor(...e){super(...e),o(this,"state",{hasError:!1,redirect:!1})}static getDerivedStateFromError(){return{hasError:!0}}componentDidCatch(e,r){console.error("ErrorBoundary caught an error",e,r),setTimeout(()=>this.setState({redirect:!0}),5e3)}render(){return this.state.redirect?(0,t.jsx)(r.Redirect,{to:"/"}):this.state.hasError?(0,t.jsxs)("h2",{children:["This listing has an error.",(0,t.jsx)(r.Link,{to:"/",children:"Click here"})," to go to home page."]}):this.props.children}}var i=s;exports.default=i;
},{}],"Uop6":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react");const t=(0,e.createContext)(["green",()=>{}]);var r=t;exports.default=r;
},{}],"SR9Y":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react"),r=require("react-dom"),t=require("react/jsx-runtime");let u;const c=c=>{u=u||document.getElementById("modal");const n=(0,e.useRef)(null);return n.current||(n.current=document.createElement("div")),(0,e.useEffect)(()=>(u.appendChild(n.current),()=>u.removeChild(n.current)),[]),(0,r.createPortal)((0,t.jsx)("div",{children:c.children}),n.current)};var n=c;exports.default=n;
},{}],"R+5f":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=c;var e=require("react"),t=require("react-router-dom"),s=a(require("./Carousel")),i=a(require("./ErrorBoundary")),o=a(require("./ThemeContext")),r=a(require("./Modal")),n=require("react/jsx-runtime");function a(e){return e&&e.__esModule?e:{default:e}}function l(e,t,s){return t in e?Object.defineProperty(e,t,{value:s,enumerable:!0,configurable:!0,writable:!0}):e[t]=s,e}class d extends e.Component{constructor(...e){super(...e),l(this,"state",{loading:!0,showModal:!1}),l(this,"onRequestClose",()=>{this.toggleModal}),l(this,"componentDidMount",async()=>{const e=await fetch(`http://pets-v2.dev-apis.com/pets?id=${this.props.match.params.id}`),t=await e.json();this.setState(Object.assign({loading:!1},t.pets[0]))}),l(this,"toggleModal",()=>this.setState({showModal:!this.state.showModal})),l(this,"adopt",()=>(window.open("http://bit.ly/pet-adopt"),"_blank"))}render(){if(this.state.loading)return(0,n.jsx)("h2",{children:"loading..."});const{animal:e,breed:t,city:i,state:a,description:l,name:d,images:u,showModal:c}=this.state;return(0,n.jsxs)("div",{className:"details",children:[(0,n.jsx)(s.default,{images:u}),(0,n.jsxs)("div",{children:[(0,n.jsx)("h1",{children:d}),(0,n.jsxs)("h2",{children:[e," - ",t," - ",i,", ",a]}),(0,n.jsx)(o.default.Consumer,{children:e=>(0,n.jsxs)("button",{onClick:this.toggleModal,style:{backgroundColor:e[0]},children:["Adopt ",d]})}),(0,n.jsx)("p",{children:l}),c?(0,n.jsx)(r.default,{children:(0,n.jsxs)("div",{children:[(0,n.jsxs)("h1",{children:["Would you like to adopt ",d,"?"]}),(0,n.jsxs)("div",{className:"buttons",children:[(0,n.jsx)("button",{onClick:this.adopt,children:"Yes"}),(0,n.jsx)("button",{onClick:this.toggleModal,children:"No"})]})]})}):null]})]})}}const u=(0,t.withRouter)(d);function c(){return(0,n.jsx)(i.default,{children:(0,n.jsx)(u,{})})}
},{"./Carousel":"q7Av","./ErrorBoundary":"izif","./ThemeContext":"Uop6","./Modal":"SR9Y"}],"F20g":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=s;var e=require("react");const t={};function s(s){const[a,r]=(0,e.useState)([]);return(0,e.useEffect)(()=>{s?t[s]?r(t[s]):async function(){r([]);const e=await fetch(`http://pets-v2.dev-apis.com/breeds?animal=${s}`),a=await e.json();t[s]=a.breeds||[],r(t[s])}():r([])},[s]),[a]}
},{}],"ys7c":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react-router-dom"),s=require("react/jsx-runtime");const r=({name:r,animal:t,breed:i,images:a,location:n,id:l})=>{let c="http://pets-images.dev-apis.com/pets/none.jpg";return a.length&&(c=a[0]),(0,s.jsxs)(e.Link,{to:`/details/${l}`,className:"pet",children:[(0,s.jsx)("div",{className:"image-container",children:(0,s.jsx)("img",{src:c,alt:r})}),(0,s.jsxs)("div",{className:"info",children:[(0,s.jsx)("h1",{children:r}),(0,s.jsx)("h2",{children:`${t} - ${i} - ${n}`})]})]})};var t=r;exports.default=t;
},{}],"eK6O":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=a(require("./Pet")),t=require("react/jsx-runtime");function a(e){return e&&e.__esModule?e:{default:e}}const r=({pets:a})=>(0,t.jsx)("div",{className:"search",children:a.length?a.map(({name:a,animal:r,breed:s,id:i,images:d,city:n,state:l})=>(0,t.jsx)(e.default,{name:a,animal:r,breed:s,images:d,location:`${n}, ${l}`,id:i},i)):(0,t.jsx)("h2",{children:"No Pets Found"})});var s=r;exports.default=s;
},{"./Pet":"ys7c"}],"zsGP":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react"),t=s(require("./ThemeContext")),a=s(require("./useBreedList")),r=s(require("./Results")),l=require("react/jsx-runtime");function s(e){return e&&e.__esModule?e:{default:e}}const n=Object.freeze(["bird","cat","dog","rabbit","reptile"]),i=()=>{const[s,i]=(0,e.useState)(""),[o,u]=(0,e.useState)(""),[d,c]=(0,e.useState)(""),[h,p]=(0,e.useState)([]),[x]=(0,a.default)(o),[v,j]=(0,e.useContext)(t.default);async function m(){const e=await fetch(`http://pets-v2.dev-apis.com/pets?animal=${o}&location=${s}&breed=${d}`),t=await e.json();p(t.pets)}return(0,e.useEffect)(()=>{m()},[]),(0,l.jsxs)("div",{className:"search-params",children:[(0,l.jsxs)("form",{onSubmit:e=>{e.preventDefault(),m()},children:[(0,l.jsxs)("label",{htmlFor:"location",children:["Location",(0,l.jsx)("input",{id:"location",value:s,placeholder:"Location",onChange:e=>i(e.target.value)})]}),(0,l.jsxs)("label",{htmlFor:"animal",children:["Animal",(0,l.jsxs)("select",{id:"animal",value:o,onChange:e=>u(e.target.value),onBlur:e=>u(e.target.value),children:[(0,l.jsx)("option",{}),n.map(e=>(0,l.jsx)("option",{value:e,children:e},e))]})]}),(0,l.jsxs)("label",{htmlFor:"breed",children:["Breed",(0,l.jsxs)("select",{disabled:!x.length,id:"breed",value:d,onChange:e=>c(e.target.value),onBlur:e=>c(e.target.value),children:[(0,l.jsx)("option",{}),x.map(e=>(0,l.jsx)("option",{value:e,children:e},e))]})]}),(0,l.jsxs)("label",{htmlFor:"theme",children:["theme",(0,l.jsxs)("select",{value:v,onChange:e=>j(e.target.value),onBlur:e=>j(e.target.value),children:[(0,l.jsx)("option",{value:"darkblue",children:"Dark Blue"}),(0,l.jsx)("option",{value:"mediumorchid",children:"Medium Orchid"}),(0,l.jsx)("option",{value:"peru",children:"Peru"}),(0,l.jsx)("option",{value:"chartreuse",children:"Chartreuse"})]})]}),(0,l.jsx)("button",{style:{backgroundColor:v},children:"Submit"})]}),(0,l.jsx)(r.default,{pets:h})]})};var o=i;exports.default=o;
},{"./ThemeContext":"Uop6","./useBreedList":"F20g","./Results":"eK6O"}],"wF8h":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react"),r=require("react-router-dom"),t=u(require("./Details")),d=u(require("./SearchParams")),i=u(require("./ThemeContext")),s=require("react/jsx-runtime");function u(e){return e&&e.__esModule?e:{default:e}}const a=()=>{const u=(0,e.useState)("darkblue");return(0,s.jsx)(e.StrictMode,{children:(0,s.jsx)(i.default.Provider,{value:u,children:(0,s.jsxs)("div",{children:[(0,s.jsx)("header",{children:(0,s.jsx)(r.Link,{to:"/",children:"Adopt Me!"})}),(0,s.jsxs)(r.Switch,{children:[(0,s.jsx)(r.Route,{path:"/details/:id",children:(0,s.jsx)(t.default,{})}),(0,s.jsx)(r.Route,{path:"/",children:(0,s.jsx)(d.default,{})})]})]})})})};var l=a;exports.default=l;
},{"./Details":"R+5f","./SearchParams":"zsGP","./ThemeContext":"Uop6"}],"Focm":[function(require,module,exports) {
"use strict";var e=o(require("express")),t=require("react-dom/server"),r=require("react-router-dom"),s=o(require("fs")),n=o(require("../src/components/App")),i=require("react/jsx-runtime");function o(e){return e&&e.__esModule?e:{default:e}}const u=process.env.PORT||3e3,d=s.default.readFileSync("dist/index.html").toString(),l=d.split("not rendered"),c=(0,e.default)();c.use("/dist",e.default.static("dist")),c.use((e,s)=>{s.write(l[0]);const o={},u=(0,i.jsx)(r.StaticRouter,{url:e.url,context:o,children:(0,i.jsx)(n.default,{})}),d=(0,t.renderToNodeStream)(u);d.pipe(s,{end:!1}),d.on("end",()=>{s.status(o.statusCode||200),s.write(l[1]),s.end()})}),console.log(`listening on http://localhost:${u}`),c.listen(u);
},{"../src/components/App":"wF8h"}]},{},["Focm"], null)
//# sourceMappingURL=/index.js.map